---
- name: Criar VM no OpenShift Virtualization
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "fedo1"
    vm_namespace: "vms"
    vm_user: "fedora"
    vm_password: "123redhat"
    vm_memory_gib: 2  # Valor em GiB
    vm_cores: 2
    vm_sockets: 1
    vm_threads: 1
    vm_storage: "30Gi"
    vm_network: "default/vlan224"
    vm_datasource_name: "fedora"
    vm_datasource_namespace: "openshift-virtualization-os-images"

  tasks:
    - name: Criar VM com CPU, Memória, Disco e Rede definidos
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_namespace }}"
          spec:
            runStrategy: RerunOnFailure
            dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  name: "{{ vm_name }}"
                spec:
                  sourceRef:
                    kind: DataSource
                    name: "{{ vm_datasource_name }}"
                    namespace: "{{ vm_datasource_namespace }}"
                  storage:
                    resources:
                      requests:
                        storage: "{{ vm_storage }}"
            template:
              metadata:
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
              spec:
                domain:
                  cpu:
                    cores: "{{ vm_cores | int }}"
                    sockets: "{{ vm_sockets | int }}"
                    threads: "{{ vm_threads | int }}"
                  memory:
                    guest: "{{ vm_memory_gib | int * 1024 * 1024 * 1024 }}"
                  devices:
                    disks:
                      - name: rootdisk
                        disk:
                          bus: virtio
                      - name: cloudinitdisk
                        disk:
                          bus: virtio
                    interfaces:
                      - name: default
                        bridge: {}
                networks:
                  - name: default
                    multus:
                      networkName: "{{ vm_network }}"
                volumes:
                  - name: rootdisk
                    dataVolume:
                      name: "{{ vm_name }}"
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        user: {{ vm_user }}
                        password: {{ vm_password }}
                        chpasswd: { expire: False }
