apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snapshot-cleaner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snapshot-cleaner-role
subjects:
  - kind: ServiceAccount
    name: snapshot-cleaner-sa
    namespace: petrobras-infra-tools