apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshot-cleaner-cronjob
  namespace: petrobras-infra-tools
spec:
  # Executar a cada 6 horas (mais frequente para políticas baseadas em horas)
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: snapshot-cleaner
        spec:
          serviceAccountName: snapshot-cleaner-sa
          restartPolicy: OnFailure
          containers:
            - name: snapshot-cleaner
              image: quay.io/fcalomen/snapshot-cleaner:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: snapshot-cleaner-config
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL