apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-vmdata
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
    - name: br-vmdata
      description: A dedicated OVS bridge with bond0 as a port allowing all VLANs
      type: ovs-bridge
      state: up
      mtu: 9000
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: false
        port:
        - name: bond0
    ovn:
      bridge-mappings:
        - bridge: br-vmdata
          localnet: vmnet
          state: present